{"uuid": "728010bc-66bc-45e7-92e0-5014eeae11d6", "children": ["7d923bc9-2c22-41f3-ba69-791f12a9cdcd"], "befores": [{"name": "ios_only", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: [BROWSERSTACK_INVALID_APP_URL] The app_url/ custom_id/ shareable_id specified in the 'app' capability in your test script is invalid. Please update the 'app' capability with a valid value and try again. Refer to this document to reset the app capabilities : https://www.browserstack.com/docs/app-automate/appium/set-up-tests/specify-app#BrowserStack_SDK\n\n", "trace": "  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/kuznetsova/Cursor/Homework_L19/tests/conftest.py\", line 126, in ios_only\n    browser.config.driver = webdriver.Remote(\n                            ^^^^^^^^^^^^^^^^^\n  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/kuznetsova/Cursor/Homework_L19/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1745410082164, "stop": 1745410084144}], "start": 1745410082164, "stop": 1745410084177}